version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ../data:/app/data
    command: python app.py

  # Optional: Add a database service if you want to use PostgreSQL instead
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: ecommerce
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
